### ISSUE TITLE
Complete README.md

### ISSUE THREAD

**Issue by bcalou** [melvinDebot/histocom-groupe-15#1]
Il vous faut remplir le README.md avec une courte présentation de votre projet.
Vous devez lister vos choix techniques justifiés.
Reprenez le Notion si besoin, sans suivre la liste à la lettre, adaptez.

Attention, il s'agit d'un préambule à l'argumentation plus détaillée que vous aurez à écrire d'ici la fin du projet. Mais j'aimerais voir ce README dès maintenant car cela vous impose vous poser les questions techniques nécessaires au démarrage.

**Comment by bcalou** [comment]
Bien, je vous laisse fermer l'issue.
Lisez quand même ça : https://rmc.bfmtv.com/emission/les-enfants-equipes-de-smartphone-a-l-age-de-9-ans-en-moyenne-1856256.html

**Comment by 11Geoffreyg** [comment]
issue closed
